In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving insurance_data (1).csv to insurance_data (1).csv


In [ ]:
df = pd.read_csv(list(uploaded.keys())[0])

In [ ]:
df

age  affordibility  bought_insurance
0    22              1                 0
1    25              0                 0
2    47              1                 1
3    52              0                 0
4    46              1                 1
5    56              1                 1
6    55              0                 0
7    60              0                 1
8    62              1                 1
9    61              1                 1
10   18              1                 0
11   28              1                 0
12   27              0                 0
13   29              0                 0
14   49              1                 1
15   55              1                 1
16   25              0                 1
17   58              1                 1
18   19              0                 0
19   18              1                 0
20   21              1                 0
21   26              0                 0
22   40              1                 1
23   45              1                 1
24   50              1                 1
25   54              1                 1
26   23              1                 0
27   46              1                 0

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df[['age','affordibility']],df.bought_insurance,train_size=0.8)

In [ ]:
X_train

age  affordibility
9    61              1
17   58              1
23   45              1
5    56              1
18   19              0
1    25              0
15   55              1
24   50              1
11   28              1
12   27              0
21   26              0
14   49              1
19   18              1
22   40              1
7    60              0
20   21              1
10   18              1
25   54              1
3    52              0
6    55              0
8    62              1
27   46              1

In [ ]:
X_train_scaled = X_train.copy()
X_train_scaled['age'] = X_train_scaled['age'] / 100

X_test_scaled = X_test.copy()
X_test_scaled['age'] = X_test_scaled['age'] / 100

In [ ]:
model = keras.Sequential([
    keras.layers.Dense(1, input_shape=(2,), activation='sigmoid', kernel_initializer='ones', bias_initializer='zeros')
])

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(X_train_scaled, y_train, epochs=500)

Epoch 1/500


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 835ms/step - accuracy: 0.5000 - loss: 0.6928
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5000 - loss: 0.6924
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5000 - loss: 0.6920
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5000 - loss: 0.6916
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.5000 - loss: 0.6913
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5000 - loss: 0.6909
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5000 - loss: 0.6905
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5000 - loss: 0.6901
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.6897
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.5000 - loss: 0.6894
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.5000 - loss: 0.6890
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.6886


In [ ]:
model.evaluate(X_test_scaled,y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 157ms/step - accuracy: 0.5000 - loss: 0.6963


[0.6963179707527161, 0.5]

In [ ]:
model.predict(X_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step


array([[0.66741043],
       [0.44821525],
       [0.6256933 ],
       [0.4560863 ],
       [0.6691714 ],
       [0.6238309 ]], dtype=float32)

In [ ]:
coef, intercept = model.get_weights()

In [ ]:
coef, intercept

(array([[0.7943972],
        [0.737557 ]], dtype=float32),
 array([-0.4064837], dtype=float32))

In [ ]:
loss, accuracy = model.evaluate(X_test_scaled, y_test, verbose=0)
print(f"Test Loss: {loss:.4f}, Test Accuracy: {accuracy:.4f}")

Test Loss: 0.6963, Test Accuracy: 0.5000
